alter table SEC_USER add constraint FK_SEC_USER_ON_JOBFUNCTION foreign key (JOBFUNCTION_ID) references SKILLGUARD_JOBFUNCTION(ID);
create index IDX_SEC_USER_ON_JOBFUNCTION on SEC_USER (JOBFUNCTION_ID);
