alter table SKILLGUARD_DEPARTMENT rename to SKILLGUARD_DEPARTMENT__UNUSED ;
alter table SEC_USER drop constraint FK_SEC_USER_DEPARTMENT ;
alter table SKILLGUARD_DEPARTMENT drop constraint FK_SKILLGUARD_DEPARTMENT_PARENT_DEPARTMENT ;
