alter table SKILLGUARD_JOBFUNCTION_ROLE_LINK add constraint FK_JOBROL_JOBFUNCTION foreign key (JOBFUNCTION_ID) references SKILLGUARD_JOBFUNCTION(ID);
alter table SKILLGUARD_JOBFUNCTION_ROLE_LINK add constraint FK_JOBROL_ROLE foreign key (ROLE_ID) references SKILLGUARD_ROLE(ID);
